{
  flake.modules.nixos.checkmk-server =
    {
      pkgs,
      lib,
      config,
      ...
    }:
    lib.mkMerge [
      {
        networking.firewall.allowedTCPPorts = [
          8080
          8000
        ];
      }
      # Auto-generated by compose2nix.
      {
        # Runtime
        virtualisation.podman = {
          enable = true;
          autoPrune.enable = true;
          dockerCompat = true;
        };

        # Enable container name DNS for all Podman networks.
        networking.firewall.interfaces =
          let
            matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
          in
          {
            "${matchAll}".allowedUDPPorts = [ 53 ];
          };

        virtualisation.oci-containers.backend = "podman";

        # Containers
        virtualisation.oci-containers.containers."checkmk-checkmk" = {
          image = "checkmk/check-mk-raw:2.4.0-latest";
          environment = {
            "CMK_PASSWORD" = "Juniorcisco123!";
            "TZ" = "Europe/Vienna";
          };
          volumes = [ "checkmk_monitoring:/omd/sites:rw" ];
          ports = [
            "8080:5000/tcp"
            "8000:8000/tcp"
          ];
          log-driver = "journald";
          extraOptions = [
            "--cap-add=NET_RAW"
            "--network-alias=checkmk"
            "--network=checkmk_default"
          ];
        };
        systemd.services."podman-checkmk-checkmk" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "always";
          };
          after = [
            "podman-network-checkmk_default.service"
            "podman-volume-checkmk_monitoring.service"
          ];
          requires = [
            "podman-network-checkmk_default.service"
            "podman-volume-checkmk_monitoring.service"
          ];
          partOf = [ "podman-compose-checkmk-root.target" ];
          wantedBy = [ "podman-compose-checkmk-root.target" ];
        };

        # Networks
        systemd.services."podman-network-checkmk_default" = {
          path = [ pkgs.podman ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "podman network rm -f checkmk_default";
          };
          script = ''
            podman network inspect checkmk_default || podman network create checkmk_default
          '';
          partOf = [ "podman-compose-checkmk-root.target" ];
          wantedBy = [ "podman-compose-checkmk-root.target" ];
        };

        # Volumes
        systemd.services."podman-volume-checkmk_monitoring" = {
          path = [ pkgs.podman ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          script = ''
            podman volume inspect checkmk_monitoring || podman volume create checkmk_monitoring
          '';
          partOf = [ "podman-compose-checkmk-root.target" ];
          wantedBy = [ "podman-compose-checkmk-root.target" ];
        };

        # Root service
        # When started, this will automatically create all resources and start
        # the containers. When stopped, this will teardown all resources.
        systemd.targets."podman-compose-checkmk-root" = {
          unitConfig = {
            Description = "Root target generated by compose2nix.";
          };
          wantedBy = [ "multi-user.target" ];
        };
      }
    ];
}
